# Default Spring Profile
server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.cardealership: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

spring:
  data:
    mongodb:
      username: user
      password: pwd
      host: localhost
      port: 0
      database: orders-db
      authentication-database: admin
      auto-index-creation: true

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.5

app:
  restaurant-service:
    host: localhost
    port: 7001
  clients-service:
    host: localhost
    port: 7002
  deliverydriver-service:
    host: localhost
    port: 7003

---
spring:
  config:
    activate:
      on-profile: docker

spring.data.mongodb.host: mongodb
spring.data.mongodb.port: 27017

app:
  restaurant-service:
    host: restaurant-service
    port: 8080
  clients-service:
    host: clients-service
    port: 8080
  deliverydriver-service:
    host: deliverydriver-service
    port: 8080


server.port: 8080